# Generated by Django 5.0.6 on 2026-04-02 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('facility', '0001_initial'),
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tasks', to='workers.worker'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='facility.room'),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='booked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_bookings', to='events.event'),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='facility.room'),
        ),
    ]
