# Generated by Django 5.0.6 on 2026-04-02 10:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('event_type', models.CharField(blank=True, help_text='e.g. BIRTHDAY, WELCOME, RECEIPT', max_length=100)),
                ('subject', models.CharField(blank=True, help_text='Email subject line', max_length=300)),
                ('body', models.TextField(help_text='Use {{first_name}}, {{amount}}, {{date}}, {{church_name}} etc.')),
                ('is_html', models.BooleanField(default=False, help_text='For email: use HTML body')),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['channel', 'name'],
                'unique_together': {('channel', 'event_type', 'is_default')},
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('channels', models.JSONField(default=list, help_text='["email", "sms"]')),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField()),
                ('target_group', models.CharField(choices=[('all_active', 'All Active Members'), ('cell_group', 'Specific Cell Group'), ('zone', 'Specific Zone'), ('visitors', 'Visitors'), ('custom', 'Custom Filter')], default='all_active', max_length=50)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_cell_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cellgroup')),
                ('target_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.zone')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.messagetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('recipient', models.CharField(help_text='Phone/email/WhatsApp number', max_length=200)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('provider_reference', models.CharField(blank=True, max_length=300)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cost_units', models.PositiveIntegerField(default=1, help_text='SMS credit units used')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='members.member')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'status'], name='communicati_channel_e5b0e8_idx')],
            },
        ),
    ]
