# Generated by Django 5.0.6 on 2026-04-02 10:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(default='My Church', max_length=200)),
                ('church_tagline', models.CharField(blank=True, max_length=300)),
                ('church_denomination', models.CharField(blank=True, max_length=150)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Ghana', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('po_box', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='church/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='church/favicon/')),
                ('primary_color', models.CharField(default='#1a6b3c', max_length=7)),
                ('secondary_color', models.CharField(default='#2c2c2c', max_length=7)),
                ('accent_color', models.CharField(default='#c9a84c', max_length=7)),
                ('currency_code', models.CharField(default='GHS', max_length=3)),
                ('currency_symbol', models.CharField(default='₵', max_length=5)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=30)),
                ('time_zone', models.CharField(default='Africa/Accra', max_length=60)),
                ('financial_year_start_month', models.PositiveSmallIntegerField(default=1)),
                ('member_number_prefix', models.CharField(default='CHR', max_length=10)),
                ('member_number_padding', models.PositiveSmallIntegerField(default=4)),
                ('enable_birthday_email', models.BooleanField(default=True)),
                ('enable_birthday_sms', models.BooleanField(default=True)),
                ('enable_birthday_whatsapp', models.BooleanField(default=False)),
                ('birthday_greeting_hour', models.PositiveSmallIntegerField(default=7)),
                ('enable_payment_receipt_email', models.BooleanField(default=True)),
                ('enable_payment_receipt_sms', models.BooleanField(default=True)),
                ('enable_event_reminders', models.BooleanField(default=True)),
                ('paystack_public_key', models.CharField(blank=True, max_length=200)),
                ('paystack_secret_key', models.CharField(blank=True, max_length=200)),
                ('twilio_account_sid', models.CharField(blank=True, max_length=100)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=100)),
                ('twilio_sender_id', models.CharField(blank=True, max_length=20)),
                ('sendgrid_api_key', models.CharField(blank=True, max_length=200)),
                ('whatsapp_api_token', models.CharField(blank=True, max_length=300)),
                ('whatsapp_phone_id', models.CharField(blank=True, max_length=100)),
                ('enable_ai_features', models.BooleanField(default=False)),
                ('ai_weekly_briefing', models.BooleanField(default=False)),
                ('ai_briefing_recipients', models.TextField(blank=True, help_text='Comma-separated email addresses for weekly AI briefing')),
                ('session_timeout_minutes', models.PositiveIntegerField(default=480)),
                ('require_2fa_for_finance', models.BooleanField(default=False)),
                ('require_2fa_for_admin', models.BooleanField(default=False)),
                ('procurement_approval_threshold_1', models.DecimalField(decimal_places=2, default=500, help_text='Amount above which single approval is required', max_digits=12)),
                ('procurement_approval_threshold_2', models.DecimalField(decimal_places=2, default=5000, help_text='Amount above which double approval is required', max_digits=12)),
            ],
            options={
                'verbose_name': 'Church Settings',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, help_text='0=Monday … 6=Sunday', null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=True)),
                ('color', models.CharField(default='#1a6b3c', max_length=7)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CellGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('meeting_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('meeting_time', models.TimeField(blank=True, null=True)),
                ('meeting_location', models.CharField(blank=True, max_length=300)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_groups', to='core.zone')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
