# Generated by Django 5.0.6 on 2026-04-02 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discipleship', '0001_initial'),
        ('members', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipleshipclass',
            name='facilitator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitated_classes', to='workers.worker'),
        ),
        migrations.AddField(
            model_name='discipleshipenrollment',
            name='discipleship_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='discipleship.discipleshipclass'),
        ),
        migrations.AddField(
            model_name='discipleshipenrollment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipleship_enrollments', to='members.member'),
        ),
        migrations.AddField(
            model_name='discipleshipclass',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='discipleship.discipleshiptrack'),
        ),
        migrations.AlterUniqueTogether(
            name='discipleshipenrollment',
            unique_together={('member', 'discipleship_class')},
        ),
    ]
