# Generated by Django 5.0.6 on 2026-04-02 10:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('finance', 'Financial'), ('data', 'Data Integrity'), ('security', 'Security'), ('compliance', 'Compliance')], max_length=20)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('is_enabled', models.BooleanField(default=True)),
                ('check_function', models.CharField(help_text='Dotted path to check function', max_length=200)),
                ('run_schedule', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('warning', 'Warning')], max_length=10)),
                ('result_summary', models.TextField()),
                ('result_detail', models.JSONField(default=dict)),
                ('affected_count', models.PositiveIntegerField(default=0)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ai_explanation', models.TextField(blank=True)),
                ('audit_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='audit.auditcheck')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
    ]
