# Generated by Django 5.0.6 on 2026-04-02 10:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('member_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('preferred_name', models.CharField(blank=True, help_text='Name they go by', max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced'), ('separated', 'Separated')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/')),
                ('national_id', models.CharField(blank=True, max_length=50)),
                ('phone_primary', models.CharField(max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Ghana', max_length=100)),
                ('whatsapp_number', models.CharField(blank=True, help_text='If different from primary phone', max_length=20)),
                ('membership_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('visitor', 'Visitor'), ('transferred_out', 'Transferred Out'), ('transferred_in', 'Transferred In'), ('deceased', 'Deceased'), ('excommunicated', 'Excommunicated')], default='visitor', max_length=20)),
                ('membership_date', models.DateField(blank=True, help_text='Date of full membership', null=True)),
                ('visitor_date', models.DateField(blank=True, help_text='Date first visited', null=True)),
                ('salvation_date', models.DateField(blank=True, null=True)),
                ('baptism_date', models.DateField(blank=True, null=True)),
                ('baptism_type', models.CharField(blank=True, help_text='Water, Holy Spirit, etc.', max_length=50)),
                ('came_from_church', models.CharField(blank=True, help_text='Previous church if transferred in', max_length=200)),
                ('spiritual_gifts', models.TextField(blank=True)),
                ('ministry_interests', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('employer', models.CharField(blank=True, max_length=200)),
                ('education_level', models.CharField(blank=True, max_length=100)),
                ('children_count', models.PositiveSmallIntegerField(default=0)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100)),
                ('receive_sms', models.BooleanField(default=True)),
                ('receive_email', models.BooleanField(default=True)),
                ('receive_whatsapp', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Internal pastoral notes')),
                ('status_changed_date', models.DateField(blank=True, null=True)),
                ('status_change_reason', models.TextField(blank=True)),
                ('transferred_to_church', models.CharField(blank=True, max_length=200)),
                ('cell_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.cellgroup')),
                ('spouse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse_of', to='members.member')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.zone')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='MemberDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='members/documents/')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='members.member')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='members.member')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['membership_status'], name='members_mem_members_6be344_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['date_of_birth'], name='members_mem_date_of_14e3af_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['phone_primary'], name='members_mem_phone_p_547098_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['email'], name='members_mem_email_afed21_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['member_number'], name='members_mem_member__425bc1_idx'),
        ),
    ]
