# Generated by Django 5.0.6 on 2026-04-02 10:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SermonSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('artwork', models.ImageField(blank=True, null=True, upload_to='sermons/series/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Sermon Series',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='sermons/speakers/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_external', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=400)),
                ('date', models.DateField()),
                ('primary_scripture', models.CharField(blank=True, help_text='e.g. John 3:16', max_length=200)),
                ('secondary_scriptures', models.TextField(blank=True, help_text='Other references, comma-separated')),
                ('topics', models.JSONField(blank=True, default=list, help_text='List of topic strings')),
                ('notes_pdf', models.FileField(blank=True, null=True, upload_to='sermons/notes/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='sermons/audio/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL')),
                ('description', models.TextField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_key_points', models.JSONField(blank=True, default=list)),
                ('ai_scriptures_extracted', models.JSONField(blank=True, default=list)),
                ('transcript_generated_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicetype')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons', to='sermons.sermonseries')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons', to='sermons.speaker')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='sermons_ser_date_01c0c3_idx'), models.Index(fields=['speaker'], name='sermons_ser_speaker_825811_idx')],
            },
        ),
    ]
